Document: spooftooph
Title: Debian spooftooph Manual
Author: <insert document author here>
Abstract: This manual describes what spooftooph is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/spooftooph/spooftooph.sgml.gz

Format: postscript
Files: /usr/share/doc/spooftooph/spooftooph.ps.gz

Format: text
Files: /usr/share/doc/spooftooph/spooftooph.text.gz

Format: HTML
Index: /usr/share/doc/spooftooph/html/index.html
Files: /usr/share/doc/spooftooph/html/*.html
